# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manhinhquetcamera.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_GiaoDienCamera(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1117, 779)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 10, 351, 71))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 270, 171, 51))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 430, 141, 51))
        self.label_3.setObjectName("label_3")
        self.batcamera_btt = QtWidgets.QPushButton(self.centralwidget)
        self.batcamera_btt.setGeometry(QtCore.QRect(250, 520, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.batcamera_btt.setFont(font)
        self.batcamera_btt.setObjectName("batcamera_btt")
        self.tatcamera_btt = QtWidgets.QPushButton(self.centralwidget)
        self.tatcamera_btt.setGeometry(QtCore.QRect(760, 510, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tatcamera_btt.setFont(font)
        self.tatcamera_btt.setObjectName("tatcamera_btt")
        self.quaylai1_btt = QtWidgets.QPushButton(self.centralwidget)
        self.quaylai1_btt.setGeometry(QtCore.QRect(510, 610, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.quaylai1_btt.setFont(font)
        self.quaylai1_btt.setObjectName("quaylai1_btt")
        self.mayanh_lb = QtWidgets.QLabel(self.centralwidget)
        self.mayanh_lb.setGeometry(QtCore.QRect(420, 100, 291, 191))
        self.mayanh_lb.setText("")
        self.mayanh_lb.setObjectName("mayanh_lb")
        self.noidungcamera_line = QtWidgets.QLineEdit(self.centralwidget)
        self.noidungcamera_line.setGeometry(QtCore.QRect(160, 341, 831, 51))
        self.noidungcamera_line.setObjectName("noidungcamera_line")
        self.trangthai_lb = QtWidgets.QLabel(self.centralwidget)
        self.trangthai_lb.setGeometry(QtCore.QRect(170, 440, 141, 31))
        self.trangthai_lb.setText("")
        self.trangthai_lb.setObjectName("trangthai_lb")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1117, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">QUÉT QR BẰNG CAMERA</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Nội dung QR:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Trạng thái:</span></p></body></html>"))
        self.batcamera_btt.setText(_translate("MainWindow", "BẬT CAMERA"))
        self.tatcamera_btt.setText(_translate("MainWindow", "TẮT CAMERA"))
        self.quaylai1_btt.setText(_translate("MainWindow", "QUAY LẠI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_GiaoDienCamera()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
