# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manhinhchinh.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_ManHinhChinh(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1118, 766)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 110, 521, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tao_btt = QtWidgets.QPushButton(self.centralwidget)
        self.tao_btt.setGeometry(QtCore.QRect(60, 200, 391, 81))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.tao_btt.setFont(font)
        self.tao_btt.setStyleSheet("QPushButton {\n"
"    background-color: #2EA7FF;   /* xanh giống hình */\n"
"    color: #FFFFFF;              /* chữ trắng */\n"
"    border: none;\n"
"    border-radius: 18px;         /* bo tròn viên thuốc */\n"
"    padding: 6px 16px;\n"
"    font-size: 25px;\n"
"    font-weight: 500;\n"
"}\n"
"")
        self.tao_btt.setObjectName("tao_btt")
        self.camera_btt = QtWidgets.QPushButton(self.centralwidget)
        self.camera_btt.setGeometry(QtCore.QRect(480, 200, 131, 81))
        self.camera_btt.setStyleSheet("QPushButton {\n"
"    background-color: #2EA7FF;   /* xanh giống hình */\n"
"    color: #FFFFFF;              /* chữ trắng */\n"
"    border: none;\n"
"    border-radius: 18px;         /* bo tròn viên thuốc */\n"
"    padding: 6px 16px;\n"
"    font-weight: 500;\n"
"}")
        self.camera_btt.setText("")
        self.camera_btt.setObjectName("camera_btt")
        self.anh_btt = QtWidgets.QPushButton(self.centralwidget)
        self.anh_btt.setGeometry(QtCore.QRect(60, 320, 551, 81))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.anh_btt.setFont(font)
        self.anh_btt.setStyleSheet("QPushButton {\n"
"    background-color: #2F80ED;   /* xanh dương đậm vừa, rất dễ nhìn */\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 18px;\n"
"    padding: 6px 16px;\n"
"    font-size: 25px;\n"
"    font-weight: 500;\n"
"}\n"
"")
        self.anh_btt.setObjectName("anh_btt")
        self.huongdan_btt = QtWidgets.QPushButton(self.centralwidget)
        self.huongdan_btt.setGeometry(QtCore.QRect(60, 440, 551, 81))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.huongdan_btt.setFont(font)
        self.huongdan_btt.setStyleSheet("QPushButton {\n"
"    background-color: #2F80ED;   /* xanh dương đậm vừa, rất dễ nhìn */\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 18px;\n"
"    padding: 6px 16px;\n"
"    font-size: 25px;\n"
"    font-weight: 500;\n"
"}\n"
"")
        self.huongdan_btt.setObjectName("huongdan_btt")
        self.thoat_btt = QtWidgets.QPushButton(self.centralwidget)
        self.thoat_btt.setGeometry(QtCore.QRect(250, 560, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.thoat_btt.setFont(font)
        self.thoat_btt.setStyleSheet("QPushButton {\n"
"    background-color: #E74C3C;   /* đỏ giống nút Thoát trong hình */\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 18px;\n"
"    padding: 6px 16px;\n"
"    font-size: 25px;\n"
"    font-weight: 500;\n"
"}\n"
"")
        self.thoat_btt.setObjectName("thoat_btt")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, -10, 1131, 791))
        self.label_2.setStyleSheet("background-image: url(:/nen/nen8.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(670, 180, 391, 411))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 18px;\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(670, 190, 391, 261))
        self.label_3.setStyleSheet("image: url(:/nen/trangtriqr.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(650, 390, 431, 221))
        self.label_4.setStyleSheet("image: url(:/nen/trangtri3.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 210, 101, 61))
        self.label_5.setStyleSheet("image: url(:/nen/trangtritaoqr.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(490, 200, 111, 81))
        self.label_6.setStyleSheet("image: url(:/nen/trangtriquetcamera.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(500, 330, 91, 61))
        self.label_7.setStyleSheet("image: url(:/nen/trangtriquetanh1.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_2.raise_()
        self.tao_btt.raise_()
        self.label.raise_()
        self.camera_btt.raise_()
        self.anh_btt.raise_()
        self.huongdan_btt.raise_()
        self.thoat_btt.raise_()
        self.pushButton.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1118, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">QR &amp; BARCODE STUDIO</span></p></body></html>"))
        self.tao_btt.setText(_translate("MainWindow", "   Tạo Mã QR"))
        self.anh_btt.setText(_translate("MainWindow", "Quét QR && Barcode từ ảnh"))
        self.huongdan_btt.setText(_translate("MainWindow", "Hướng Dẫn Sử Dụng"))
        self.thoat_btt.setText(_translate("MainWindow", "Thoát"))
import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_ManHinhChinh()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
