# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manhinhhd.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_GiaoDienHuongDan(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1116, 779)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1121, 761))
        self.label.setStyleSheet("background-image: url(:/nen/nen8.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(400, 70, 351, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(670, 160, 391, 411))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 18px;\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(670, 180, 391, 261))
        self.label_3.setStyleSheet("image: url(:/nen/trangtriqr.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(650, 390, 431, 221))
        self.label_4.setStyleSheet("image: url(:/nen/trangtri3.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 140, 581, 521))
        self.label_5.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 20); /* nền trong suốt nhẹ */\n"
"    border: 2px solid rgba(120, 200, 255, 180); /* viền xanh sáng */\n"
"    border-radius: 8\n"
"}")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(80, 150, 54, 54))
        self.label_6.setStyleSheet("QLabel {\n"
"    background-color: rgb(255, 245, 200);   /* vàng nhạt */\n"
"    color: rgb(180, 120, 0);                 /* vàng đậm (chữ) */\n"
"    border: 2px solid rgb(200, 150, 0);      /* viền vàng đậm */\n"
"    border-radius: 25px;                     /* bo tròn */\n"
"    min-width: 50px;\n"
"    min-height: 50px;\n"
"    max-width: 50px;\n"
"    max-height: 50px;\n"
"    font-weight: bold;\n"
"    font-size: 16px;\n"
"    qproperty-alignment: AlignCenter;        /* chữ nằm giữa */\n"
"}\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(150, 160, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel {\n"
"    color: rgb(255, 215, 0);   /* vàng */\n"
"}\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(150, 290, 55, 16))
        self.label_9.setObjectName("label_9")
        self.ql_btt = QtWidgets.QPushButton(self.centralwidget)
        self.ql_btt.setGeometry(QtCore.QRect(770, 610, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.ql_btt.setFont(font)
        self.ql_btt.setStyleSheet("QPushButton {\n"
"    background-color: #2F80ED;   /* xanh dương đậm vừa, rất dễ nhìn */\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 18px;\n"
"    padding: 6px 16px;\n"
"    font-size: 22px;\n"
"    font-weight: 500;\n"
"}")
        self.ql_btt.setObjectName("ql_btt")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(780, 620, 61, 51))
        self.label_10.setStyleSheet("image: url(:/nen/quaylai1.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(80, 320, 54, 54))
        self.label_11.setStyleSheet("QLabel {\n"
"    background-color: rgb(255, 220, 190);   /* cam nhạt */\n"
"    color: rgb(200, 90, 0);                  /* cam đậm (chữ) */\n"
"    border: 2px solid rgb(220, 120, 20);     /* viền cam đậm */\n"
"    border-radius: 25px;                     /* bo tròn */\n"
"    min-width: 50px;\n"
"    min-height: 50px;\n"
"    max-width: 50px;\n"
"    max-height: 50px;\n"
"    font-weight: bold;\n"
"    font-size: 16px;\n"
"    qproperty-alignment: AlignCenter;        /* chữ nằm giữa */\n"
"}\n"
"")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(150, 330, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(200, 90, 0);                  /* cam đậm (chữ) */")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(80, 510, 54, 54))
        self.label_13.setStyleSheet("QLabel {\n"
"    background-color: rgb(200, 230, 255);   /* xanh biển nhạt */\n"
"    color: rgb(0, 90, 160);                  /* xanh biển đậm (chữ) */\n"
"    border: 2px solid rgb(0, 120, 200);      /* viền xanh biển đậm */\n"
"    border-radius: 25px;                     /* bo tròn */\n"
"    min-width: 50px;\n"
"    min-height: 50px;\n"
"    max-width: 50px;\n"
"    max-height: 50px;\n"
"    font-weight: bold;\n"
"    font-size: 16px;\n"
"    qproperty-alignment: AlignCenter;        /* chữ nằm giữa */\n"
"}\n"
"")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(150, 530, 281, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(200, 230, 255);   /* xanh biển nhạt")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(90, 210, 441, 101))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(80, 380, 511, 131))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(80, 570, 561, 71))
        self.label_17.setObjectName("label_17")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1116, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">HƯỚNG DẪN SỬ DỤNG</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "1"))
        self.label_7.setText(_translate("MainWindow", "Tạo QR Code"))
        self.label_9.setText(_translate("MainWindow", "- "))
        self.ql_btt.setText(_translate("MainWindow", "      Quay lại"))
        self.label_11.setText(_translate("MainWindow", "2"))
        self.label_12.setText(_translate("MainWindow", "Quét mã QR bằng camera"))
        self.label_13.setText(_translate("MainWindow", "3"))
        self.label_14.setText(_translate("MainWindow", "Quét QR & Barcode từ ảnh"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">- Nhập nội dung (text / link).</span></p><p><span style=\" color:#ffffff;\">- Nhấn TẠO QR để tạo mã.</span></p><p><span style=\" color:#ffffff;\">- Có thể LƯU QR.</span></p><p><span style=\" color:#ffffff;\">- Nhấn XÓA để thiết lập giao diện về mặc định, QUAY LẠI về giao diện chính.</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt; color:#ffffff;\">- Nhấn BẬT CAMERA để mở camrera quét mã QR.</span></p><p><span style=\" font-size:7pt; color:#ffffff;\">- Đưa mã QR vào khung camera, hệ thống sẽ tự động nhận diện và hiển thị nội dung.</span></p><p><span style=\" font-size:7pt; color:#ffffff;\">- Theo dõi Trạng thái để biết camera đang hoạt động.</span></p><p><span style=\" font-size:7pt; color:#ffffff;\">- Nhấn TẮT CAMERA để tắt camera và dừng quét.</span></p><p><span style=\" font-size:7pt; color:#ffffff;\">- Nhấn XÓA để thiết lập giao diện về mặc định, QUAY LẠI về giao diện chính.</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">- Nhấn CHỌN ẢNH để tải ảnh chứa QR/Barcode.</span></p><p><span style=\" color:#ffffff;\">- Hệ thống tự động quét xác định vùng ảnh có chứa QR/Barcode và hiển thị Nội dung và Loại mã.</span></p><p><span style=\" color:#ffffff;\">- Nhấn XÓA để thiết lập giao diện về mặc định, QUAY LẠI về giao diện chính.</span></p></body></html>"))
import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_GiaoDienHuongDan()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
