# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manhinhquetanh.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_GiaoDienQuetAnh(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1117, 780)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 50, 421, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.chonanh_btt = QtWidgets.QPushButton(self.centralwidget)
        self.chonanh_btt.setGeometry(QtCore.QRect(160, 580, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.chonanh_btt.setFont(font)
        self.chonanh_btt.setStyleSheet("QPushButton {\n"
"    background-color: #2F80ED;   /* xanh dương đậm vừa, rất dễ nhìn */\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 18px;\n"
"    padding: 6px 16px;\n"
"    font-size: 22px;\n"
"    font-weight: 500;\n"
"}\n"
"")
        self.chonanh_btt.setObjectName("chonanh_btt")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 390, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 480, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.quaylai2_btt = QtWidgets.QPushButton(self.centralwidget)
        self.quaylai2_btt.setGeometry(QtCore.QRect(740, 580, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.quaylai2_btt.setFont(font)
        self.quaylai2_btt.setStyleSheet("QPushButton {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 18px;\n"
"    font-size: 22px;\n"
"}")
        self.quaylai2_btt.setObjectName("quaylai2_btt")
        self.noidunganh_line = QtWidgets.QLineEdit(self.centralwidget)
        self.noidunganh_line.setGeometry(QtCore.QRect(230, 400, 661, 51))
        self.noidunganh_line.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;     /* nền trắng */\n"
"    color: #333333;                /* chữ xám đậm */\n"
"    border: 1px solid #BDBDBD;     /* viền xám nhạt */\n"
"    border-radius: 12px;           /* bo tròn góc */\n"
"    padding: 6px 12px;             /* khoảng cách chữ */\n"
"    font-size: 14px;\n"
"}")
        self.noidunganh_line.setObjectName("noidunganh_line")
        self.loaima_lb = QtWidgets.QLabel(self.centralwidget)
        self.loaima_lb.setGeometry(QtCore.QRect(230, 480, 661, 51))
        self.loaima_lb.setStyleSheet("QLabel {\n"
"    /* Nền trắng trong suốt nhẹ giúp nổi bật trên hình nền xanh đậm */\n"
"    background-color: rgba(255, 255, 255, 20); \n"
"    \n"
"    /* Viền xanh sáng tạo hiệu ứng công nghệ hiện đại */\n"
"    border: 2px solid rgba(120, 200, 255, 180); \n"
"    \n"
"    /* Bo góc khung */\n"
"    border-radius: 8px;\n"
"    \n"
"    /* Đổi màu chữ sang trắng để dễ đọc nhất */\n"
"    color: #ffffff;\n"
"    \n"
"    /* Làm đậm chữ để tăng độ nhận diện */\n"
"    font-weight: bold;\n"
"    \n"
"    /* Đẩy chữ cách viền trái một chút cho cân đối */\n"
"    padding-left: 10px;\n"
"}")
        self.loaima_lb.setText("")
        self.loaima_lb.setObjectName("loaima_lb")
        self.qrbarcode1_lb = QtWidgets.QLabel(self.centralwidget)
        self.qrbarcode1_lb.setGeometry(QtCore.QRect(250, 180, 241, 161))
        self.qrbarcode1_lb.setText("")
        self.qrbarcode1_lb.setObjectName("qrbarcode1_lb")
        self.qrbarcode2_lb = QtWidgets.QLabel(self.centralwidget)
        self.qrbarcode2_lb.setGeometry(QtCore.QRect(640, 180, 241, 161))
        self.qrbarcode2_lb.setText("")
        self.qrbarcode2_lb.setObjectName("qrbarcode2_lb")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 1121, 761))
        self.label_4.setStyleSheet("background-image: url(:/nen/nen8.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(590, 150, 341, 221))
        self.label_5.setStyleSheet("image: url(:/nen/khungcamera1.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(220, 150, 301, 221))
        self.label_6.setStyleSheet("image: url(:/nen/khungcamera1.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.xoa3_btt = QtWidgets.QPushButton(self.centralwidget)
        self.xoa3_btt.setGeometry(QtCore.QRect(450, 580, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.xoa3_btt.setFont(font)
        self.xoa3_btt.setStyleSheet("QPushButton {\n"
"    background-color: #E74C3C;   /* đỏ giống nút Thoát trong hình */\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 18px;\n"
"    padding: 6px 16px;\n"
"    font-size: 22px;\n"
"    font-weight: 500;\n"
"}")
        self.xoa3_btt.setObjectName("xoa3_btt")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(170, 590, 61, 41))
        self.label_7.setStyleSheet("image: url(:/nen/trangtriquetanh1.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(754, 580, 61, 61))
        self.label_8.setStyleSheet("image: url(:/nen/quaylai.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(480, 590, 55, 41))
        self.label_9.setStyleSheet("image: url(:/nen/xoa.png);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(680, 220, 21, 16))
        self.label_10.setStyleSheet("image: url(:/nen/nenche.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_4.raise_()
        self.label_10.raise_()
        self.label_6.raise_()
        self.label_5.raise_()
        self.label.raise_()
        self.chonanh_btt.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.noidunganh_line.raise_()
        self.loaima_lb.raise_()
        self.qrbarcode1_lb.raise_()
        self.qrbarcode2_lb.raise_()
        self.xoa3_btt.raise_()
        self.quaylai2_btt.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1117, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">QUÉT QR &amp; BARCODE TỪ ẢNH</span></p></body></html>"))
        self.chonanh_btt.setText(_translate("MainWindow", "     Chọn ảnh"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Nội dung :</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Loại mã : </span></p></body></html>"))
        self.quaylai2_btt.setText(_translate("MainWindow", "    Quay lại"))
        self.xoa3_btt.setText(_translate("MainWindow", "  Xóa"))
import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_GiaoDienQuetAnh()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
