# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manhinhtaoqr.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_GiaoDienTaoQR(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1119, 779)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 50, 531, 81))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 130, 381, 111))
        self.label_2.setObjectName("label_2")
        self.taoqr_btt = QtWidgets.QPushButton(self.centralwidget)
        self.taoqr_btt.setGeometry(QtCore.QRect(110, 380, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.taoqr_btt.setFont(font)
        self.taoqr_btt.setObjectName("taoqr_btt")
        self.luuqr_btt = QtWidgets.QPushButton(self.centralwidget)
        self.luuqr_btt.setGeometry(QtCore.QRect(850, 380, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.luuqr_btt.setFont(font)
        self.luuqr_btt.setObjectName("luuqr_btt")
        self.quaylai_btt = QtWidgets.QPushButton(self.centralwidget)
        self.quaylai_btt.setGeometry(QtCore.QRect(480, 630, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.quaylai_btt.setFont(font)
        self.quaylai_btt.setObjectName("quaylai_btt")
        self.noidungqr_line = QtWidgets.QLineEdit(self.centralwidget)
        self.noidungqr_line.setGeometry(QtCore.QRect(280, 221, 541, 51))
        self.noidungqr_line.setObjectName("noidungqr_line")
        self.anhqr_lb = QtWidgets.QLabel(self.centralwidget)
        self.anhqr_lb.setGeometry(QtCore.QRect(360, 360, 401, 211))
        self.anhqr_lb.setText("")
        self.anhqr_lb.setObjectName("anhqr_lb")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1119, 26))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.label.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">TẠO QR CODE</span></p></body></html>"))
        self.label_2.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Nhập nội dung:</span></p></body></html>"))
        self.taoqr_btt.setText(_translate("mainWindow", "TẠO QR"))
        self.luuqr_btt.setText(_translate("mainWindow", "LƯU QR"))
        self.quaylai_btt.setText(_translate("mainWindow", "QUAY LẠI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_GiaoDienTaoQR()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
